"""Piece 9 seed data — Electric Loads Calculator / System Sizing.
Ported from the standalone loads_calculator.html field tool.
APPLIANCE_SEED: (name, category, era, low_w, high_w, avg_w, hrs_per_day, usage_type, notes)
COMPONENT_SEED: (name, category, manufacturer, model, specs, watts, voc, vmp,
                 temp_coef_voc, capacity_kwh_nameplate, dod, max_input_v,
                 continuous_w, inverter_eff, cost, notes)
"""

APPLIANCE_SEED = [
    ('Refrigerator, modern (top-freezer)', 'Kitchen', 'Modern', 100, 200, 150, 8, 'Always-on', 'Energy Star 2010+'),
    ('Refrigerator, vintage (pre-1990)', 'Kitchen', 'Vintage', 200, 500, 350, 12, 'Always-on', 'Older compressors run much longer'),
    ('Refrigerator, side-by-side modern', 'Kitchen', 'Modern', 150, 250, 200, 8, 'Always-on', 'Ice maker adds ~100W'),
    ('Refrigerator, side-by-side vintage', 'Kitchen', 'Vintage', 300, 600, 450, 10, 'Always-on', 'Very common in NM rural homes'),
    ('Refrigerator, mini-fridge', 'Kitchen', 'Modern', 50, 100, 75, 8, 'Always-on', None),
    ('Chest freezer, modern', 'Kitchen', 'Modern', 60, 120, 90, 8, 'Always-on', 'Energy Star rated'),
    ('Chest freezer, vintage', 'Kitchen', 'Vintage', 150, 350, 250, 10, 'Always-on', 'Pre-1995, very inefficient'),
    ('Upright freezer, modern', 'Kitchen', 'Modern', 80, 150, 115, 8, 'Always-on', None),
    ('Upright freezer, vintage', 'Kitchen', 'Vintage', 200, 400, 300, 10, 'Always-on', 'Pre-1995'),
    ('Electric range / oven (full size)', 'Kitchen', 'Modern', 3000, 5000, 4000, 1, 'Occupied', 'Per use cycle'),
    ('Electric range, vintage coil top', 'Kitchen', 'Vintage', 3500, 5500, 4500, 1, 'Occupied', 'Coil elements run hotter/longer'),
    ('Electric oven only (wall mount)', 'Kitchen', 'Modern', 2000, 5000, 3500, 1, 'Occupied', None),
    ('Microwave, countertop', 'Kitchen', 'Modern', 600, 1500, 1050, 0.5, 'Occupied', None),
    ('Microwave, vintage (1980s-90s)', 'Kitchen', 'Vintage', 800, 1800, 1300, 0.5, 'Occupied', 'Less efficient magnetrons'),
    ('Dishwasher, modern', 'Kitchen', 'Modern', 1200, 2400, 1800, 1, 'Occupied', 'Heating element is the big load'),
    ('Dishwasher, vintage', 'Kitchen', 'Vintage', 1800, 3200, 2500, 1.5, 'Occupied', 'Older heating elements + motors'),
    ('Coffee maker, drip', 'Kitchen', 'Modern', 600, 1500, 1050, 0.25, 'Occupied', None),
    ('Percolator, electric (vintage)', 'Kitchen', 'Vintage', 600, 1200, 900, 0.3, 'Occupied', 'Common in older NM kitchens'),
    ('Toaster', 'Kitchen', 'Modern', 700, 1100, 900, 0.1, 'Occupied', None),
    ('Toaster oven', 'Kitchen', 'Modern', 1000, 1800, 1400, 0.25, 'Occupied', None),
    ('Blender', 'Kitchen', 'Modern', 300, 900, 600, 0.1, 'Occupied', None),
    ('Stand mixer', 'Kitchen', 'Modern', 300, 600, 450, 0.1, 'Occupied', None),
    ('Food processor', 'Kitchen', 'Modern', 200, 800, 500, 0.1, 'Occupied', None),
    ('Slow cooker (Crock-Pot)', 'Kitchen', 'Modern', 75, 200, 138, 6, 'Occupied', None),
    ('Instant Pot / pressure cooker', 'Kitchen', 'Modern', 700, 1200, 950, 0.5, 'Occupied', None),
    ('Electric griddle', 'Kitchen', 'Modern', 1000, 1800, 1400, 0.5, 'Occupied', None),
    ('Electric skillet (vintage)', 'Kitchen', 'Vintage', 1000, 1500, 1250, 0.5, 'Occupied', 'Very common in older NM homes'),
    ('Range hood / exhaust fan', 'Kitchen', 'Modern', 65, 400, 233, 1, 'Occupied', None),
    ('Under-cabinet lighting, fluorescent', 'Kitchen', 'Vintage', 20, 60, 40, 6, 'Occupied', 'T12 strip lights'),
    ('Under-cabinet lighting, LED', 'Kitchen', 'Modern', 10, 30, 20, 6, 'Occupied', None),
    ('Garbage disposal', 'Kitchen', 'Modern', 370, 900, 635, 0.1, 'Occupied', None),
    ('Water cooler / dispenser', 'Kitchen', 'Modern', 75, 200, 138, 24, 'Always-on', 'Heating + cooling element'),
    ('Electric kettle', 'Kitchen', 'Modern', 1000, 1800, 1400, 0.1, 'Occupied', None),
    ('Bread machine', 'Kitchen', 'Modern', 500, 700, 600, 2, 'Occupied', None),
    ('Trash compactor', 'Kitchen', 'Vintage', 400, 1000, 700, 0.1, 'Occupied', 'Common in older homes'),
    ('Washing machine, front-load modern', 'Laundry', 'Modern', 300, 700, 500, 1, 'Occupied', None),
    ('Washing machine, top-load modern', 'Laundry', 'Modern', 400, 900, 650, 1, 'Occupied', None),
    ('Washing machine, vintage top-load', 'Laundry', 'Vintage', 700, 1500, 1100, 1.5, 'Occupied', 'Agitator models pre-2000'),
    ('Washing machine, wringer (antique)', 'Laundry', 'Vintage', 200, 500, 350, 1, 'Occupied', 'Still found in rural NM'),
    ('Electric dryer, modern', 'Laundry', 'Modern', 4000, 6000, 5000, 1, 'Occupied', '240V circuit'),
    ('Electric dryer, vintage', 'Laundry', 'Vintage', 5000, 7500, 6250, 1.5, 'Occupied', 'Older heating elements'),
    ('Dryer, gas (electric motor only)', 'Laundry', 'Modern', 300, 500, 400, 1, 'Occupied', 'Motor + controls only'),
    ('Clothes iron', 'Laundry', 'Modern', 1000, 2400, 1700, 0.5, 'Occupied', None),
    ('Sewing machine, electric modern', 'Laundry', 'Modern', 100, 250, 175, 1, 'Occupied', None),
    ('Sewing machine, vintage (1950s-70s)', 'Laundry', 'Vintage', 75, 150, 113, 1, 'Occupied', 'Lower draw, heavy motors'),
    ('Dehumidifier', 'Laundry', 'Modern', 300, 900, 600, 12, 'Seasonal', 'Damp months'),
    ('Central AC (2 ton)', 'HVAC', 'Modern', 1800, 2500, 2150, 8, 'Seasonal', None),
    ('Central AC (3 ton)', 'HVAC', 'Modern', 2500, 3800, 3150, 8, 'Seasonal', None),
    ('Central AC (4 ton)', 'HVAC', 'Modern', 3500, 5000, 4250, 8, 'Seasonal', None),
    ('Central AC, vintage (pre-1995)', 'HVAC', 'Vintage', 4000, 8000, 6000, 10, 'Seasonal', 'SEER 6-8 vs 14+ modern'),
    ('Window AC unit (5,000 BTU)', 'HVAC', 'Modern', 500, 700, 600, 8, 'Seasonal', None),
    ('Window AC unit (10,000 BTU)', 'HVAC', 'Modern', 900, 1200, 1050, 8, 'Seasonal', None),
    ('Window AC unit (12,000 BTU)', 'HVAC', 'Modern', 1100, 1500, 1300, 8, 'Seasonal', None),
    ('Window AC, vintage (1960s-80s)', 'HVAC', 'Vintage', 1500, 3000, 2250, 10, 'Seasonal', 'Much higher draw than modern'),
    ('Mini split (9,000 BTU / 0.75 ton)', 'HVAC', 'Modern', 700, 900, 800, 10, 'Seasonal', None),
    ('Mini split (12,000 BTU / 1 ton)', 'HVAC', 'Modern', 900, 1200, 1050, 10, 'Seasonal', None),
    ('Mini split (18,000 BTU / 1.5 ton)', 'HVAC', 'Modern', 1300, 1800, 1550, 10, 'Seasonal', None),
    ('Mini split (24,000 BTU / 2 ton)', 'HVAC', 'Modern', 1800, 2400, 2100, 10, 'Seasonal', None),
    ('Heat pump (2 ton central)', 'HVAC', 'Modern', 1800, 3000, 2400, 10, 'Seasonal', 'Heating and cooling'),
    ('Heat pump (3 ton central)', 'HVAC', 'Modern', 2500, 4000, 3250, 10, 'Seasonal', None),
    ('Air handler / blower motor', 'HVAC', 'Modern', 300, 800, 550, 8, 'Occupied', 'Runs with any forced-air system'),
    ('Evaporative cooler, small', 'HVAC', 'Modern', 100, 300, 200, 10, 'Seasonal', 'Very common in NM'),
    ('Evaporative cooler, whole-house', 'HVAC', 'Modern', 250, 700, 475, 10, 'Seasonal', None),
    ('Evaporative cooler, vintage', 'HVAC', 'Vintage', 300, 800, 550, 12, 'Seasonal', 'Older motors less efficient'),
    ('Electric baseboard heater (per 4 ft)', 'HVAC', 'Modern', 750, 1500, 1125, 8, 'Seasonal', '240V'),
    ('Electric baseboard, vintage', 'HVAC', 'Vintage', 750, 1750, 1250, 10, 'Seasonal', 'Older thermostats waste more'),
    ('Electric wall heater (fan-forced)', 'HVAC', 'Modern', 1500, 4000, 2750, 6, 'Seasonal', None),
    ('Gas/propane furnace, fan only', 'HVAC', 'Modern', 500, 800, 650, 8, 'Seasonal', 'Motor + controls; fuel does heating'),
    ('Whole-house fan', 'HVAC', 'Modern', 600, 1200, 900, 4, 'Seasonal', None),
    ('Attic fan', 'HVAC', 'Modern', 150, 400, 275, 6, 'Seasonal', None),
    ('ERV / HRV unit', 'HVAC', 'Modern', 100, 300, 200, 24, 'Always-on', 'Continuous ventilation'),
    ('Ceiling fan', 'HVAC', 'Modern', 15, 75, 45, 8, 'Occupied', None),
    ('Ceiling fan, vintage (1970s-80s)', 'HVAC', 'Vintage', 50, 120, 85, 8, 'Occupied', 'Larger, heavier motors'),
    ('Box / window fan', 'HVAC', 'Modern', 50, 200, 125, 8, 'Occupied', None),
    ('Portable space heater, radiant', 'HVAC', 'Modern', 750, 1500, 1125, 6, 'Seasonal', None),
    ('Portable oil-filled radiator', 'HVAC', 'Modern', 600, 1500, 1050, 8, 'Seasonal', None),
    ('Pellet stove, electric auger + blower', 'HVAC', 'Modern', 75, 125, 100, 8, 'Seasonal', 'Pellet fuel; motor is electric'),
    ('LED lighting (per room)', 'Lighting', 'Modern', 10, 60, 35, 5, 'Occupied', None),
    ('CFL lighting (per room)', 'Lighting', 'Modern', 20, 80, 50, 5, 'Occupied', 'Transitional era'),
    ('Incandescent lighting (per room)', 'Lighting', 'Vintage', 120, 400, 260, 5, 'Occupied', 'Typical 2-4 fixture room'),
    ('Fluorescent tube lights, T8 (4-lamp)', 'Lighting', 'Modern', 80, 160, 120, 8, 'Occupied', None),
    ('Fluorescent, vintage T12 (magnetic)', 'Lighting', 'Vintage', 80, 200, 140, 8, 'Occupied', 'Magnetic ballast adds loss'),
    ('Halogen track lighting (3-4 heads)', 'Lighting', 'Vintage', 150, 500, 325, 4, 'Occupied', None),
    ('Outdoor security lights, LED', 'Lighting', 'Modern', 20, 100, 60, 10, 'Always-on', None),
    ('Outdoor security lights, HPS/MH', 'Lighting', 'Vintage', 70, 250, 160, 10, 'Always-on', 'High-pressure sodium/metal halide'),
    ('Outdoor flood lights, incandescent', 'Lighting', 'Vintage', 150, 500, 325, 6, 'Occupied', None),
    ('Landscape lighting, low-volt LED', 'Lighting', 'Modern', 5, 50, 28, 8, 'Always-on', 'Per zone'),
    ('Yard light / pole light, HPS', 'Lighting', 'Vintage', 100, 250, 175, 12, 'Always-on', 'Dusk-to-dawn'),
    ('Night lights (plug-in)', 'Lighting', 'Modern', 1, 7, 4, 12, 'Always-on', 'LED vs incandescent'),
    ('TV (32" LED/LCD)', 'Entertainment', 'Modern', 30, 60, 45, 5, 'Occupied', None),
    ('TV (55" LED/LCD)', 'Entertainment', 'Modern', 60, 120, 90, 5, 'Occupied', None),
    ('TV (65" LED/LCD)', 'Entertainment', 'Modern', 100, 170, 135, 5, 'Occupied', None),
    ('TV (70"+)', 'Entertainment', 'Modern', 120, 250, 185, 5, 'Occupied', None),
    ('CRT television (25")', 'Entertainment', 'Vintage', 100, 170, 135, 5, 'Occupied', 'Very common in rural NM'),
    ('CRT television (32"+)', 'Entertainment', 'Vintage', 150, 250, 200, 5, 'Occupied', None),
    ('CRT projection TV', 'Entertainment', 'Vintage', 200, 400, 300, 4, 'Occupied', None),
    ('Satellite receiver / DVR', 'Entertainment', 'Modern', 15, 45, 30, 24, 'Always-on', 'Standby power significant'),
    ('Cable / satellite box (vintage)', 'Entertainment', 'Vintage', 15, 35, 25, 24, 'Always-on', 'Always drawing power'),
    ('Streaming stick (Roku/Fire/Apple)', 'Entertainment', 'Modern', 2, 5, 4, 5, 'Occupied', None),
    ('DVD player', 'Entertainment', 'Modern', 10, 25, 18, 2, 'Occupied', None),
    ('VCR (vintage)', 'Entertainment', 'Vintage', 15, 40, 28, 2, 'Occupied', 'Standby always on'),
    ('Stereo receiver, modern', 'Entertainment', 'Modern', 20, 100, 60, 4, 'Occupied', None),
    ('Stereo receiver, vintage (1970s-80s)', 'Entertainment', 'Vintage', 50, 350, 200, 4, 'Occupied', 'Heavy iron transformers'),
    ('Turntable + preamp', 'Entertainment', 'Vintage', 5, 25, 15, 2, 'Occupied', None),
    ('Console record player / hi-fi cabinet', 'Entertainment', 'Vintage', 50, 150, 100, 2, 'Occupied', 'All-in-one, common in NM'),
    ('Reel-to-reel tape deck', 'Entertainment', 'Vintage', 30, 80, 55, 2, 'Occupied', None),
    ('8-track player', 'Entertainment', 'Vintage', 20, 60, 40, 2, 'Occupied', 'Still found in rural NM'),
    ('Whole-house stereo amplifier', 'Entertainment', 'Vintage', 100, 400, 250, 3, 'Occupied', 'Built-in systems 1970s-80s'),
    ('Subwoofer / powered speakers', 'Entertainment', 'Modern', 20, 200, 110, 4, 'Occupied', None),
    ('Gaming console (PS5/XBox Series X)', 'Entertainment', 'Modern', 100, 200, 150, 3, 'Occupied', None),
    ('Gaming console (older gen)', 'Entertainment', 'Modern', 70, 150, 110, 3, 'Occupied', None),
    ('Projector, home theater', 'Entertainment', 'Modern', 150, 350, 250, 2, 'Occupied', None),
    ('Desktop PC, modern efficient', 'Office', 'Modern', 60, 200, 130, 8, 'Occupied', None),
    ('Desktop PC, vintage tower (2000s)', 'Office', 'Vintage', 200, 500, 350, 8, 'Occupied', 'Older PSUs 60-70% efficient'),
    ('Desktop PC, gaming (high-end)', 'Office', 'Modern', 300, 700, 500, 4, 'Occupied', None),
    ('Laptop / notebook', 'Office', 'Modern', 30, 100, 65, 8, 'Occupied', None),
    ('Monitor (24" LED)', 'Office', 'Modern', 20, 35, 28, 8, 'Occupied', None),
    ('CRT monitor (17"-21")', 'Office', 'Vintage', 60, 140, 100, 8, 'Occupied', None),
    ('Printer, inkjet', 'Office', 'Modern', 8, 30, 19, 1, 'Occupied', None),
    ('Printer, laser', 'Office', 'Modern', 300, 1000, 650, 0.5, 'Occupied', 'Fuser element, high draw'),
    ('Fax machine', 'Office', 'Vintage', 5, 30, 18, 0.5, 'Always-on', 'Standby always on'),
    ('Answering machine, vintage', 'Office', 'Vintage', 3, 8, 6, 24, 'Always-on', None),
    ('Intercom system, wired (1970s-80s)', 'Office', 'Vintage', 5, 25, 15, 24, 'Always-on', 'Whole-house systems'),
    ('Ham radio transceiver', 'Office', 'Modern', 50, 200, 125, 2, 'Occupied', 'Common in rural NM'),
    ('CB radio base station', 'Office', 'Vintage', 10, 50, 30, 2, 'Occupied', None),
    ('Modem (cable/DSL)', 'Office', 'Modern', 6, 15, 11, 24, 'Always-on', None),
    ('Wifi router', 'Office', 'Modern', 5, 20, 13, 24, 'Always-on', None),
    ('Network switch', 'Office', 'Modern', 5, 15, 10, 24, 'Always-on', None),
    ('UPS (uninterruptible power supply)', 'Office', 'Modern', 20, 60, 40, 24, 'Always-on', 'Standby draw'),
    ('Cordless phone base station', 'Office', 'Modern', 2, 5, 4, 24, 'Always-on', None),
    ('Electric water heater (40-gal)', 'Water Heating', 'Modern', 3500, 5500, 4500, 3, 'Always-on', 'Runs 2-4 hr/day avg'),
    ('Electric water heater, vintage', 'Water Heating', 'Vintage', 4000, 6000, 5000, 4, 'Always-on', 'Less insulation, runs longer'),
    ('Electric water heater (80-gal)', 'Water Heating', 'Modern', 4000, 6000, 5000, 5, 'Always-on', None),
    ('Electric tankless water heater', 'Water Heating', 'Modern', 10000, 27000, 18500, 0.5, 'Always-on', 'Very high instantaneous draw'),
    ('Heat pump water heater', 'Water Heating', 'Modern', 500, 1000, 750, 2, 'Always-on', '3-4x more efficient than resistance'),
    ('Propane water heater, power vent', 'Water Heating', 'Modern', 25, 80, 53, 2, 'Always-on', 'Blower motor only'),
    ('Solar water heater, electric backup', 'Water Heating', 'Modern', 1500, 4500, 3000, 1, 'Always-on', 'Backup element only'),
    ('Well pump (1/2 HP submersible)', 'Water', 'Modern', 370, 500, 435, 2, 'Always-on', None),
    ('Well pump (3/4 HP submersible)', 'Water', 'Modern', 550, 750, 650, 2, 'Always-on', None),
    ('Well pump (1 HP submersible)', 'Water', 'Modern', 750, 1000, 875, 2, 'Always-on', None),
    ('Well pump (1-1/2 HP submersible)', 'Water', 'Modern', 1100, 1500, 1300, 2, 'Always-on', None),
    ('Well pump (2 HP submersible)', 'Water', 'Modern', 1500, 2000, 1750, 2, 'Always-on', 'Deeper wells, larger homes'),
    ('Well pump, vintage piston type', 'Water', 'Vintage', 500, 1500, 1000, 3, 'Always-on', 'Much less efficient, common in NM'),
    ('Pressure tank booster pump', 'Water', 'Modern', 250, 750, 500, 1, 'Always-on', None),
    ('Sump pump', 'Water', 'Modern', 300, 800, 550, 0.5, 'Seasonal', None),
    ('Irrigation / sprinkler pump (1 HP)', 'Water', 'Modern', 750, 1000, 875, 2, 'Seasonal', None),
    ('Irrigation pump, large (2 HP)', 'Water', 'Modern', 1500, 2000, 1750, 3, 'Seasonal', None),
    ('Pool pump (1 HP)', 'Water', 'Modern', 750, 1000, 875, 6, 'Seasonal', None),
    ('Pool pump (1-1/2 HP)', 'Water', 'Modern', 1100, 1500, 1300, 6, 'Seasonal', None),
    ('Pool pump, vintage single-speed', 'Water', 'Vintage', 1200, 2000, 1600, 8, 'Seasonal', 'Variable speed far more efficient'),
    ('Hot tub / spa pump + heater', 'Water', 'Modern', 2000, 6000, 4000, 1, 'Seasonal', None),
    ('Garage door opener (1/2 HP)', 'Garage', 'Modern', 300, 500, 400, 0.1, 'Occupied', None),
    ('Garage door opener, vintage chain', 'Garage', 'Vintage', 400, 600, 500, 0.1, 'Occupied', None),
    ('Air compressor, small shop (1.5 HP)', 'Garage', 'Modern', 900, 1800, 1350, 0.5, 'Occupied', None),
    ('Air compressor, large tank (3-5 HP)', 'Garage', 'Modern', 1500, 3700, 2600, 1, 'Occupied', None),
    ('Air compressor, vintage upright', 'Garage', 'Vintage', 1200, 2500, 1850, 1, 'Occupied', 'Less efficient single-stage'),
    ('Table saw (10")', 'Garage', 'Modern', 1500, 2500, 2000, 0.5, 'Occupied', None),
    ('Radial arm saw (vintage)', 'Garage', 'Vintage', 1500, 2500, 2000, 0.5, 'Occupied', 'Common in older workshops'),
    ('Circular saw (corded)', 'Garage', 'Modern', 1200, 2000, 1600, 0.2, 'Occupied', None),
    ('Angle grinder (4.5")', 'Garage', 'Modern', 700, 1500, 1100, 0.3, 'Occupied', None),
    ('Bench grinder', 'Garage', 'Modern', 200, 500, 350, 0.3, 'Occupied', None),
    ('Shop vacuum', 'Garage', 'Modern', 500, 1200, 850, 0.5, 'Occupied', None),
    ('Welder, MIG (120V)', 'Garage', 'Modern', 800, 1800, 1300, 1, 'Occupied', None),
    ('Welder, arc stick (240V)', 'Garage', 'Modern', 3000, 8000, 5500, 1, 'Occupied', None),
    ('Plasma cutter', 'Garage', 'Modern', 2000, 6000, 4000, 0.5, 'Occupied', None),
    ('Bandsaw (shop)', 'Garage', 'Modern', 300, 800, 550, 0.3, 'Occupied', None),
    ('Drill press', 'Garage', 'Modern', 500, 900, 700, 0.3, 'Occupied', None),
    ('Lathe, wood (small)', 'Garage', 'Modern', 500, 900, 700, 1, 'Occupied', None),
    ('Dust collector (shop)', 'Garage', 'Modern', 750, 1500, 1125, 2, 'Occupied', None),
    ('Battery charger (12V standard)', 'Garage', 'Modern', 6, 15, 11, 4, 'Occupied', None),
    ('Battery charger, trickle (float)', 'Garage', 'Modern', 1, 5, 3, 24, 'Always-on', 'Maintenance mode'),
    ('Central vacuum system', 'Garage', 'Modern', 500, 1200, 850, 0.5, 'Occupied', None),
    ('EV charger, Level 1 (120V/12A)', 'EV Charging', 'Modern', 1200, 1440, 1320, 8, 'Occupied', '~4 mi/hr; built-in cable (EVSE)'),
    ('EV charger, Level 1 (120V/16A)', 'EV Charging', 'Modern', 1600, 1920, 1760, 8, 'Occupied', 'Some older EVSEs draw up to 1.9kW'),
    ('EV charger, Level 2 (240V/16A)', 'EV Charging', 'Modern', 3200, 3840, 3520, 4, 'Occupied', '~12 mi/hr; older EVs'),
    ('EV charger, Level 2 (240V/24A)', 'EV Charging', 'Modern', 4800, 5760, 5280, 4, 'Occupied', '~18 mi/hr'),
    ('EV charger, Level 2 (240V/32A)', 'EV Charging', 'Modern', 6400, 7680, 7040, 4, 'Occupied', '~25 mi/hr; most common home install'),
    ('EV charger, Level 2 (240V/40A)', 'EV Charging', 'Modern', 8000, 9600, 8800, 3, 'Occupied', '~30 mi/hr; Tesla HPWC typical'),
    ('EV charger, Level 2 (240V/48A)', 'EV Charging', 'Modern', 9600, 11520, 10560, 3, 'Occupied', '~37 mi/hr; max for most home panels'),
    ('EV charger, Level 2 (240V/60A)', 'EV Charging', 'Modern', 12000, 14400, 13200, 2.5, 'Occupied', '~45 mi/hr; needs 75A breaker'),
    ('EV charger, Level 2 (240V/80A)', 'EV Charging', 'Modern', 16000, 19200, 17600, 2, 'Occupied', '~60 mi/hr; large commercial/home'),
    ('EV charger, DC fast (Level 3, 50kW)', 'EV Charging', 'Modern', 40000, 50000, 45000, 0.5, 'Occupied', 'Commercial/fleet; rare residential'),
    ('EV charger, bidirectional (V2H)', 'EV Charging', 'Modern', 7200, 11500, 9350, 3, 'Occupied', 'Vehicle-to-home; can export power'),
    ('EV charger, vintage (Gen 1 Leaf)', 'EV Charging', 'Vintage', 3300, 3600, 3450, 6, 'Occupied', '240V/15A'),
    ('EVSE wall unit, idle standby', 'EV Charging', 'Modern', 1, 5, 3, 24, 'Always-on', 'Network card/display draw'),
    ('Livestock water tank de-icer (250W)', 'Agricultural', 'Modern', 250, 350, 300, 12, 'Seasonal', 'Submersible, winter only'),
    ('Livestock water tank de-icer (1500W)', 'Agricultural', 'Modern', 1200, 1500, 1350, 8, 'Seasonal', 'Larger tank, colder climate'),
    ('Stock tank heater, vintage coil', 'Agricultural', 'Vintage', 1500, 2000, 1750, 10, 'Seasonal', 'Resistance coil types'),
    ('Heat lamp, brooder (250W)', 'Agricultural', 'Modern', 225, 275, 250, 16, 'Seasonal', 'Poultry brooding'),
    ('Heat lamp, brooder (500W)', 'Agricultural', 'Modern', 450, 550, 500, 14, 'Seasonal', 'Larger flocks or cold climates'),
    ('Poultry house ventilation fan', 'Agricultural', 'Modern', 100, 400, 250, 12, 'Seasonal', None),
    ('Chicken coop heater (flat panel)', 'Agricultural', 'Modern', 100, 200, 150, 10, 'Seasonal', 'Radiant; safer than heat lamps'),
    ('Incubator, egg (small tabletop)', 'Agricultural', 'Modern', 20, 100, 60, 24, 'Always-on', 'Constant temp; ~21-day cycles'),
    ('Incubator, commercial cabinet', 'Agricultural', 'Modern', 200, 800, 500, 24, 'Always-on', 'Larger flocks'),
    ('Milking machine, small (1/2 HP)', 'Agricultural', 'Modern', 370, 500, 435, 2, 'Occupied', 'Small dairy'),
    ('Milking machine, vintage piston', 'Agricultural', 'Vintage', 500, 1000, 750, 2, 'Occupied', 'Much louder/older design'),
    ('Bulk milk tank cooler, modern', 'Agricultural', 'Modern', 750, 1500, 1125, 8, 'Always-on', 'Compressor cycles all day'),
    ('Bulk milk tank, vintage', 'Agricultural', 'Vintage', 1000, 2500, 1750, 10, 'Always-on', 'Very inefficient compressor'),
    ('Electric fence energizer, AC low', 'Agricultural', 'Modern', 3, 10, 7, 24, 'Always-on', 'Plug-in, light duty'),
    ('Electric fence energizer, AC heavy', 'Agricultural', 'Modern', 10, 30, 20, 24, 'Always-on', 'Multi-mile fence lines'),
    ('Electric fence energizer, vintage', 'Agricultural', 'Vintage', 10, 50, 30, 24, 'Always-on', 'Older transformer-based'),
    ('Heat tape, pipe (self-regulating)', 'Agricultural', 'Modern', 25, 75, 50, 12, 'Seasonal', 'Per 10 ft'),
    ('Heat tape, vintage fixed-watt', 'Agricultural', 'Vintage', 50, 150, 100, 12, 'Seasonal', 'Wastes more than self-regulating'),
    ('Well pump, irrigation (5 HP)', 'Agricultural', 'Modern', 3700, 4500, 4100, 4, 'Seasonal', 'Field irrigation'),
    ('Well pump, irrigation (7.5 HP)', 'Agricultural', 'Modern', 5600, 6700, 6150, 4, 'Seasonal', None),
    ('Well pump, irrigation vintage (5 HP)', 'Agricultural', 'Vintage', 4500, 6000, 5250, 5, 'Seasonal', 'Less efficient older motors'),
    ('Grain auger, electric (5 HP)', 'Agricultural', 'Modern', 3700, 4500, 4100, 1, 'Occupied', None),
    ('Grain auger, vintage (3 HP)', 'Agricultural', 'Vintage', 2200, 3000, 2600, 1, 'Occupied', None),
    ('Feed grinder / mixer motor', 'Agricultural', 'Vintage', 1500, 5000, 3250, 1, 'Occupied', 'Varies widely by size'),
    ('Hay conveyor / elevator motor', 'Agricultural', 'Modern', 750, 2200, 1475, 1, 'Occupied', None),
    ('Barn lighting, fluorescent (per fixture)', 'Agricultural', 'Vintage', 40, 120, 80, 8, 'Occupied', 'T12 strip fixtures'),
    ('Barn lighting, LED retrofit', 'Agricultural', 'Modern', 20, 60, 40, 8, 'Occupied', None),
    ('Barn lighting, incandescent (per bulb)', 'Agricultural', 'Vintage', 60, 150, 105, 8, 'Occupied', 'Often left on all day'),
    ('Refrigerated produce cooler, walk-in', 'Agricultural', 'Modern', 1500, 4000, 2750, 24, 'Always-on', 'Small farm storage'),
    ('Water aerator / pond pump', 'Agricultural', 'Modern', 250, 750, 500, 24, 'Always-on', None),
    ('Propane furnace, blower motor', 'Propane Systems', 'Modern', 400, 800, 600, 8, 'Seasonal', 'Fan only; gas does heating'),
    ('Propane furnace, blower (vintage)', 'Propane Systems', 'Vintage', 500, 1000, 750, 8, 'Seasonal', 'Older fan motors'),
    ('Propane boiler, circulator pump', 'Propane Systems', 'Modern', 75, 250, 163, 8, 'Seasonal', 'Hot water radiant systems'),
    ('Propane boiler, vintage circulator', 'Propane Systems', 'Vintage', 100, 350, 225, 8, 'Seasonal', 'Older Taco/Bell & Gossett pumps'),
    ('Propane water heater, power vent', 'Propane Systems', 'Modern', 25, 80, 53, 2, 'Always-on', 'Blower motor for venting'),
    ('Propane range, electric ignition', 'Propane Systems', 'Modern', 3, 8, 6, 0.1, 'Occupied', 'Spark igniter only; tiny draw'),
    ('Propane range, vintage pilot light', 'Propane Systems', 'Vintage', 0, 0, 0, 0, 'Occupied', 'No electricity needed at all'),
    ('Propane dryer, electric motor', 'Propane Systems', 'Modern', 300, 500, 400, 1, 'Occupied', 'Motor + drum; propane heats'),
    ('Propane fireplace, electric blower', 'Propane Systems', 'Modern', 25, 100, 63, 4, 'Seasonal', 'Circulation fan only'),
    ('Propane room heater, vent-free', 'Propane Systems', 'Modern', 0, 5, 3, 0.1, 'Occupied', 'Near-zero; thermostat/piezo only'),
    ('Propane tank monitor (electronic)', 'Propane Systems', 'Modern', 1, 5, 3, 24, 'Always-on', 'Wireless level sensor'),
    ('Well house heater, modern', 'Well House', 'Modern', 750, 1500, 1125, 8, 'Seasonal', 'Freeze protection'),
    ('Well house heater, vintage', 'Well House', 'Vintage', 1000, 2000, 1500, 8, 'Seasonal', 'Old radiant or fan-forced'),
    ('Well house light (always on)', 'Well House', 'Vintage', 40, 100, 70, 24, 'Always-on', 'Incandescent left on for heat'),
    ('Well house light, LED', 'Well House', 'Modern', 10, 20, 15, 24, 'Always-on', 'Often left on for visibility'),
    ('Pressure switch / control box', 'Well House', 'Modern', 2, 8, 5, 24, 'Always-on', None),
    ('UV water treatment system', 'Well House', 'Modern', 25, 75, 50, 24, 'Always-on', 'UV lamp always on'),
    ('Water softener, electric valve', 'Well House', 'Modern', 2, 8, 5, 24, 'Always-on', 'Timer + valve motor only'),
    ('Chlorination / dosing pump', 'Well House', 'Modern', 10, 50, 30, 2, 'Always-on', None),
    ('Transfer switch, whole-house (standby)', 'Generator Systems', 'Modern', 5, 20, 13, 24, 'Always-on', 'Control board idle draw'),
    ('Generator battery maintainer', 'Generator Systems', 'Modern', 1, 5, 3, 24, 'Always-on', 'Keeps start battery topped'),
    ('Generator block heater', 'Generator Systems', 'Modern', 250, 1000, 625, 24, 'Seasonal', 'Cold weather starting aid'),
    ('CPAP machine', 'Medical', 'Modern', 30, 60, 45, 8, 'Always-on', None),
    ('CPAP with heated humidifier', 'Medical', 'Modern', 30, 100, 65, 8, 'Always-on', None),
    ('BiPAP machine', 'Medical', 'Modern', 30, 120, 75, 8, 'Always-on', None),
    ('Oxygen concentrator (home)', 'Medical', 'Modern', 150, 300, 225, 24, 'Always-on', None),
    ('Nebulizer', 'Medical', 'Modern', 50, 100, 75, 0.25, 'Occupied', None),
    ('Electric hospital bed (adjustable)', 'Medical', 'Modern', 100, 500, 300, 0.5, 'Occupied', 'Position motor'),
    ('Stair lift', 'Medical', 'Modern', 150, 300, 225, 0.1, 'Occupied', None),
    ('Electric wheelchair charger', 'Medical', 'Modern', 100, 300, 200, 8, 'Occupied', None),
    ('Dialysis machine (home)', 'Medical', 'Modern', 300, 750, 525, 4, 'Occupied', None),
    ('Whole-house surge protector', 'Safety', 'Modern', 1, 3, 2, 24, 'Always-on', None),
    ('Smoke detector (hardwired)', 'Safety', 'Modern', 0.5, 2, 1, 24, 'Always-on', 'Per unit'),
    ('CO / propane detector (hardwired)', 'Safety', 'Modern', 1, 3, 2, 24, 'Always-on', 'Per unit; critical in propane homes'),
    ('Security system panel + keypad', 'Safety', 'Modern', 5, 15, 10, 24, 'Always-on', None),
    ('Security camera system (4-cam NVR)', 'Safety', 'Modern', 15, 60, 38, 24, 'Always-on', None),
    ('Video doorbell', 'Safety', 'Modern', 2, 8, 5, 24, 'Always-on', None),
    ('Doorbell, wired transformer', 'Safety', 'Vintage', 2, 8, 5, 24, 'Always-on', 'Always energized'),
    ('Photovoltaic inverter (standby)', 'Solar Systems', 'Modern', 10, 30, 20, 24, 'Always-on', 'Idle draw when no solar'),
    ('Battery inverter / charger (standby)', 'Solar Systems', 'Modern', 15, 60, 38, 24, 'Always-on', 'Off-grid; Magnum, Outback, etc.'),
    ('MPPT charge controller (standby)', 'Solar Systems', 'Modern', 1, 5, 3, 24, 'Always-on', None),
    ('Battery management system (BMS)', 'Solar Systems', 'Modern', 2, 10, 6, 24, 'Always-on', 'Active BMS in lithium banks'),
    ('Data logger / monitoring system', 'Solar Systems', 'Modern', 2, 10, 6, 24, 'Always-on', None),
    ('Electric kiln, small pottery (1.8 cu ft)', 'Workshop / Craft', 'Modern', 1400, 2300, 1850, 6, 'Occupied', '240V; per firing cycle'),
    ('Electric kiln, medium (7 cu ft)', 'Workshop / Craft', 'Modern', 3500, 7000, 5250, 8, 'Occupied', '240V'),
    ('Electric kiln, vintage (1960s-70s)', 'Workshop / Craft', 'Vintage', 2000, 5000, 3500, 8, 'Occupied', 'Less insulation = longer cycles'),
    ('Pottery wheel, electric', 'Workshop / Craft', 'Modern', 100, 300, 200, 3, 'Occupied', None),
    ('Metalworking lathe (1-2 HP)', 'Workshop / Craft', 'Modern', 750, 1500, 1125, 2, 'Occupied', None),
    ('Metalworking lathe, vintage', 'Workshop / Craft', 'Vintage', 1000, 2000, 1500, 2, 'Occupied', 'Heavy single-phase motors'),
    ('Metal mill / milling machine', 'Workshop / Craft', 'Modern', 750, 2000, 1375, 2, 'Occupied', None),
    ('Wire feed welder, small (120V)', 'Workshop / Craft', 'Modern', 600, 1500, 1050, 1, 'Occupied', None),
    ('TIG welder (240V)', 'Workshop / Craft', 'Modern', 2000, 5000, 3500, 1, 'Occupied', None),
    ('Spot welder', 'Workshop / Craft', 'Modern', 1500, 4000, 2750, 0.5, 'Occupied', None),
    ('Sandblaster, electric compressor', 'Workshop / Craft', 'Modern', 1500, 3000, 2250, 1, 'Occupied', 'Compressor-dependent'),
    ('Electric pottery wheel, vintage', 'Workshop / Craft', 'Vintage', 150, 400, 275, 3, 'Occupied', 'Older Brent/Amaco models'),
    ('Glass kiln / fusing kiln', 'Workshop / Craft', 'Modern', 1200, 3000, 2100, 6, 'Occupied', None),
    ('Resin curing lamp (UV)', 'Workshop / Craft', 'Modern', 36, 100, 68, 0.5, 'Occupied', None),
    ('Scroll saw', 'Workshop / Craft', 'Modern', 100, 250, 175, 1, 'Occupied', None),
    ('Wood burning tool / pyrography', 'Workshop / Craft', 'Modern', 15, 60, 38, 1, 'Occupied', None),
    ('Loom, electric (weaving)', 'Workshop / Craft', 'Modern', 100, 300, 200, 3, 'Occupied', None),
    ('Serger / overlock machine', 'Workshop / Craft', 'Modern', 100, 200, 150, 1, 'Occupied', None),
    ('Embroidery machine, computerized', 'Workshop / Craft', 'Modern', 50, 150, 100, 2, 'Occupied', None),
    ('3D printer (FDM)', 'Workshop / Craft', 'Modern', 50, 200, 125, 6, 'Occupied', 'Heated bed dominant load'),
    ('Laser engraver (desktop, 20W)', 'Workshop / Craft', 'Modern', 100, 200, 150, 2, 'Occupied', None),
    ('Vinyl cutting machine', 'Workshop / Craft', 'Modern', 15, 50, 33, 1, 'Occupied', None),
    ('Air brush compressor (small)', 'Workshop / Craft', 'Modern', 100, 250, 175, 1, 'Occupied', None),
    ('Heat press (garment printing)', 'Workshop / Craft', 'Modern', 1000, 1800, 1400, 0.5, 'Occupied', None),
    ('Darkroom enlarger + safelight', 'Workshop / Craft', 'Vintage', 75, 200, 138, 2, 'Occupied', 'Film photography darkroom'),
    ('Satellite dish de-icer / heater', 'Communications', 'Modern', 15, 60, 38, 12, 'Seasonal', 'Snow/ice melt; common in NM mtns'),
    ('Satellite internet terminal (Starlink)', 'Communications', 'Modern', 25, 75, 50, 24, 'Always-on', 'Gen 2 dish; ~50W avg'),
    ('Satellite internet terminal, Gen 1', 'Communications', 'Modern', 65, 100, 83, 24, 'Always-on', 'Older larger dish'),
    ('DSL modem', 'Communications', 'Modern', 5, 15, 10, 24, 'Always-on', None),
    ('Cable modem', 'Communications', 'Modern', 8, 20, 14, 24, 'Always-on', None),
    ('Cell phone signal booster', 'Communications', 'Modern', 5, 25, 15, 24, 'Always-on', 'weBoost/SureCall etc.'),
    ('Ham radio, HF transceiver (receive)', 'Communications', 'Modern', 20, 60, 40, 2, 'Occupied', 'Receive mode; TX much higher'),
    ('Ham radio, HF transceiver (transmit)', 'Communications', 'Modern', 200, 1000, 600, 0.5, 'Occupied', '100W amp; key-down'),
    ('Ham radio, linear amplifier', 'Communications', 'Modern', 500, 3000, 1750, 0.3, 'Occupied', 'Contest/DX use'),
    ('GMRS/FRS base station', 'Communications', 'Modern', 5, 25, 15, 2, 'Occupied', None),
    ('Weather station, home (powered)', 'Communications', 'Modern', 2, 10, 6, 24, 'Always-on', None),
    ('AM/FM radio, tabletop', 'Communications', 'Vintage', 10, 40, 25, 4, 'Occupied', None),
    ('Shortwave radio receiver', 'Communications', 'Vintage', 10, 50, 30, 4, 'Occupied', 'Common in rural NM'),
    ('Police scanner', 'Communications', 'Modern', 5, 15, 10, 6, 'Occupied', 'Common in rural NM'),
    ('NOAA weather radio', 'Communications', 'Modern', 3, 8, 6, 24, 'Always-on', None),
    ('VOIP phone adapter (ATA)', 'Communications', 'Modern', 3, 8, 6, 24, 'Always-on', None),
    ('Electric smoker, small (400W)', 'Outdoor Cooking', 'Modern', 300, 500, 400, 4, 'Occupied', None),
    ('Electric smoker, full-size', 'Outdoor Cooking', 'Modern', 700, 1500, 1100, 6, 'Occupied', None),
    ('Electric smoker, vintage', 'Outdoor Cooking', 'Vintage', 500, 1200, 850, 6, 'Occupied', 'Older Brinkmann etc.'),
    ('Pellet grill / smoker', 'Outdoor Cooking', 'Modern', 300, 800, 550, 6, 'Occupied', 'Electric auger + igniter'),
    ('Electric rotisserie (outdoor)', 'Outdoor Cooking', 'Modern', 200, 400, 300, 2, 'Occupied', None),
    ('Outdoor electric griddle / Blackstone', 'Outdoor Cooking', 'Modern', 1400, 1800, 1600, 1, 'Occupied', None),
    ('Outdoor patio heater, electric', 'Outdoor Cooking', 'Modern', 1000, 1500, 1250, 3, 'Seasonal', 'Infrared quartz'),
    ('Electric pizza oven (countertop)', 'Outdoor Cooking', 'Modern', 1200, 1800, 1500, 0.5, 'Occupied', None),
    ('Deep fryer, electric (home)', 'Outdoor Cooking', 'Modern', 1200, 2000, 1600, 0.5, 'Occupied', None),
    ('Food dehydrator, small', 'Outdoor Cooking', 'Modern', 300, 700, 500, 8, 'Occupied', None),
    ('Food dehydrator, large commercial', 'Outdoor Cooking', 'Modern', 600, 1500, 1050, 8, 'Occupied', 'Jerky/chile drying common in NM'),
    ('Chile roaster, electric (drum)', 'Outdoor Cooking', 'Modern', 800, 1500, 1150, 0.5, 'Seasonal', 'NM-specific; August-October'),
    ('Canning jar lifter / electric canner', 'Outdoor Cooking', 'Modern', 1000, 1500, 1250, 2, 'Seasonal', 'Harvest season'),
    ('Vacuum sealer', 'Outdoor Cooking', 'Modern', 100, 300, 200, 0.2, 'Occupied', None),
    ('Meat grinder, electric', 'Outdoor Cooking', 'Modern', 300, 1200, 750, 0.5, 'Occupied', None),
    ('Sausage stuffer, electric', 'Outdoor Cooking', 'Modern', 100, 350, 225, 0.5, 'Occupied', None),
    ('Outdoor refrigerator', 'Outdoor Cooking', 'Modern', 80, 180, 130, 8, 'Always-on', None),
    ('Ice maker, standalone outdoor', 'Outdoor Cooking', 'Modern', 150, 350, 250, 8, 'Occupied', None),
    ('Pressure canner, electric', 'Outdoor Cooking', 'Modern', 900, 1500, 1200, 1.5, 'Seasonal', None),
    ('Wired baby monitor', 'Baby / Child', 'Modern', 1, 5, 3, 24, 'Always-on', None),
    ('Baby food maker / steamer', 'Baby / Child', 'Modern', 200, 400, 300, 0.25, 'Occupied', None),
    ('Electric bottle warmer', 'Baby / Child', 'Modern', 50, 200, 125, 0.1, 'Occupied', None),
    ('Electric breast pump', 'Baby / Child', 'Modern', 40, 75, 58, 0.5, 'Occupied', None),
    ('Humidifier, nursery', 'Baby / Child', 'Modern', 25, 50, 38, 8, 'Seasonal', None),
    ('Electric swing / bouncer', 'Baby / Child', 'Modern', 10, 30, 20, 4, 'Occupied', None),
    ('Baby wipe warmer', 'Baby / Child', 'Modern', 5, 15, 10, 24, 'Always-on', None),
    ('Night light, nursery', 'Baby / Child', 'Modern', 1, 7, 4, 10, 'Always-on', None),
    ('Sound machine (white noise)', 'Baby / Child', 'Modern', 2, 5, 4, 10, 'Always-on', None),
    ('Aquarium (30-gal, heater + pump)', 'Hobby / Recreation', 'Modern', 50, 150, 100, 24, 'Always-on', None),
    ('Aquarium (100+ gal)', 'Hobby / Recreation', 'Modern', 150, 400, 275, 24, 'Always-on', None),
    ('Reptile enclosure with heat', 'Hobby / Recreation', 'Modern', 75, 300, 188, 24, 'Always-on', None),
    ('Terrarium heat mat', 'Hobby / Recreation', 'Modern', 8, 25, 17, 24, 'Always-on', None),
    ('Model train layout (transformer)', 'Hobby / Recreation', 'Vintage', 50, 200, 125, 3, 'Occupied', 'HO/O scale'),
    ('Slot car racing track (vintage)', 'Hobby / Recreation', 'Vintage', 30, 80, 55, 2, 'Occupied', None),
    ('Electric guitar amplifier, small', 'Hobby / Recreation', 'Modern', 30, 100, 65, 2, 'Occupied', None),
    ('Electric guitar amplifier, vintage tube', 'Hobby / Recreation', 'Vintage', 60, 200, 130, 2, 'Occupied', 'Tube amps draw more idle'),
    ('Electric organ, Hammond B3 style', 'Hobby / Recreation', 'Vintage', 150, 350, 250, 2, 'Occupied', None),
    ('Electric piano / digital keyboard', 'Hobby / Recreation', 'Modern', 10, 50, 30, 2, 'Occupied', None),
    ('Treadmill', 'Hobby / Recreation', 'Modern', 300, 1500, 900, 1, 'Occupied', None),
    ('Exercise bike (magnetic resistance)', 'Hobby / Recreation', 'Modern', 10, 50, 30, 1, 'Occupied', None),
    ('Exercise bike, motorized (Peloton)', 'Hobby / Recreation', 'Modern', 100, 300, 200, 1, 'Occupied', None),
    ('Rowing machine (magnetic)', 'Hobby / Recreation', 'Modern', 1, 5, 3, 1, 'Occupied', 'Display only; negligible'),
    ('Air hockey table', 'Hobby / Recreation', 'Vintage', 50, 150, 100, 2, 'Occupied', None),
    ('Pinball machine, vintage', 'Hobby / Recreation', 'Vintage', 200, 400, 300, 3, 'Occupied', 'Classic electromechanical'),
    ('Jukebox, vintage (1950s-60s)', 'Hobby / Recreation', 'Vintage', 150, 300, 225, 3, 'Occupied', 'Common in NM diners/homes'),
    ('Slot machine, vintage', 'Hobby / Recreation', 'Vintage', 30, 75, 53, 3, 'Occupied', 'Electromechanical types'),
    ('Hot tub, inflatable (electric)', 'Hobby / Recreation', 'Modern', 1200, 2200, 1700, 4, 'Seasonal', None),
    ('Swamp cooler, portable', 'Hobby / Recreation', 'Modern', 100, 300, 200, 8, 'Seasonal', None),
    ('Bug zapper, outdoor', 'Hobby / Recreation', 'Modern', 20, 80, 50, 10, 'Seasonal', None),
    ('Electric boat motor charger (trolling)', 'Hobby / Recreation', 'Modern', 10, 30, 20, 6, 'Occupied', '12V lead-acid bank'),
    ('ATV / UTV battery maintainer', 'Hobby / Recreation', 'Modern', 1, 10, 6, 24, 'Always-on', None),
    ('Electric dirt bike charger', 'Hobby / Recreation', 'Modern', 300, 800, 550, 4, 'Occupied', None),
    ('Swimming pool, above-ground pump', 'Hobby / Recreation', 'Modern', 500, 900, 700, 6, 'Seasonal', None),
    ('Hot glue gun, high-temp', 'Hobby / Recreation', 'Modern', 60, 120, 90, 0.3, 'Occupied', None),
    ('Laminator (letter size)', 'Hobby / Recreation', 'Modern', 200, 400, 300, 0.2, 'Occupied', None),
    ('Electric pencil sharpener', 'Hobby / Recreation', 'Modern', 10, 30, 20, 0.05, 'Occupied', None),
    ('Christmas lights, LED (per strand)', 'Seasonal / Holiday', 'Modern', 5, 15, 10, 6, 'Seasonal', None),
    ('Christmas lights, C7/C9 incandescent', 'Seasonal / Holiday', 'Vintage', 50, 200, 125, 6, 'Seasonal', 'Per 25-50 bulb strand'),
    ('Christmas lights, mini incandescent', 'Seasonal / Holiday', 'Vintage', 20, 50, 35, 6, 'Seasonal', 'Per 100-light strand'),
    ('Inflatable holiday decoration', 'Seasonal / Holiday', 'Modern', 50, 250, 150, 8, 'Seasonal', 'Blower fan motor'),
    ('Electric menorah / chanukiah', 'Seasonal / Holiday', 'Modern', 25, 75, 50, 2, 'Seasonal', None),
    ('Christmas tree, artificial lit (LED)', 'Seasonal / Holiday', 'Modern', 10, 40, 25, 6, 'Seasonal', 'Pre-lit'),
    ('Christmas tree, vintage (incandescent)', 'Seasonal / Holiday', 'Vintage', 40, 200, 120, 6, 'Seasonal', 'Pre-lit with C7 bulbs'),
    ('Outdoor light show projector', 'Seasonal / Holiday', 'Modern', 30, 80, 55, 8, 'Seasonal', None),
    ('Electric candles (window, set of 5)', 'Seasonal / Holiday', 'Modern', 5, 15, 10, 10, 'Seasonal', None),
    ('Halloween animatronic, large', 'Seasonal / Holiday', 'Modern', 30, 100, 65, 6, 'Seasonal', None),
    ('Outdoor fountain / water feature', 'Seasonal / Holiday', 'Modern', 20, 150, 85, 12, 'Seasonal', None),
    ('Heated pet bed, small', 'Pets', 'Modern', 15, 50, 33, 12, 'Seasonal', None),
    ('Heated pet bed, large', 'Pets', 'Modern', 40, 100, 70, 12, 'Seasonal', None),
    ('Automatic pet feeder, electric', 'Pets', 'Modern', 2, 5, 4, 24, 'Always-on', None),
    ('Pet water fountain, electric', 'Pets', 'Modern', 2, 10, 6, 24, 'Always-on', None),
    ('Dog door, automatic (sensor)', 'Pets', 'Modern', 5, 20, 13, 24, 'Always-on', None),
    ('Fish tank heater (50W)', 'Pets', 'Modern', 40, 60, 50, 24, 'Always-on', 'Thermostat-controlled'),
    ('Fish tank heater (200W)', 'Pets', 'Modern', 150, 250, 200, 24, 'Always-on', 'Larger tanks'),
    ('Aquarium pump / filter', 'Pets', 'Modern', 3, 30, 17, 24, 'Always-on', None),
    ('Bird cage heat lamp', 'Pets', 'Modern', 25, 100, 63, 12, 'Seasonal', None),
    ('Electric dog fence transmitter', 'Pets', 'Modern', 3, 10, 7, 24, 'Always-on', None),
    ('Horse arena lighting (per fixture, LED)', 'Pets', 'Modern', 100, 400, 250, 4, 'Occupied', 'LED retrofit'),
    ('Horse arena lighting, metal halide', 'Pets', 'Vintage', 400, 1000, 700, 4, 'Occupied', 'Per fixture; very common in NM'),
    ('Cattle prod charger', 'Pets', 'Modern', 5, 15, 10, 1, 'Occupied', 'Battery charger only'),
]

COMPONENT_SEED = [
    ('REC Alpha Pure 2 430W', 'PV Module', 'REC', 'REC430AA', '430W · Voc 49.3V · Vmp 41.8V · Isc 10.88A · Imp 10.29A · Temp coef Voc -0.24%/°C', 430, 49.3, 41.8, -0.24, None, None, None, None, None, 320, 'High-efficiency modern residential panel.'),
    ('Q.TRON BLK M-G2+ 425W', 'PV Module', 'Q Cells', 'Q.TRON BLK M-G2+ 425', '425W · Voc 39.03V · Vmp 32.74V · Isc 13.66A · Imp 12.98A · Temp coef Voc -0.24%/°C', 425, 39.03, 32.74, -0.24, None, None, None, None, None, 300, 'Common mid-size residential module.'),
    ('Silfab SIL-400 HC+', 'PV Module', 'Silfab', 'SIL-400 HC+', '400W · Voc 43.0V · Isc 11.10A · Temp coef Voc ≈ -0.27%/°C (est.)', 400, 43.0, None, -0.27, None, None, None, None, None, 280, 'North American-manufactured panel, popular for domestic-content projects.'),
    ('Canadian Solar HiHero 430W', 'PV Module', 'Canadian Solar', 'CS6R-430H-AG', '430W · Voc 40.1V · Vmp 33.8V · Isc 13.38A · Imp 12.76A · Temp coef Voc -0.24%/°C', 430, 40.1, 33.8, -0.24, None, None, None, None, None, 280, ''),
    ('Jinko Tiger Neo 440W', 'PV Module', 'Jinko Solar', '54HL4R-B 440W', '440W · Voc 39.57V · Vmp 32.99V · Isc 13.80A · Imp 13.34A · Temp coef Voc ≈ -0.25%/°C (est.)', 440, 39.57, 32.99, -0.25, None, None, None, None, None, 170, 'Budget-tier high-output panel.'),
    ('Tesla Powerwall 3', 'Battery', 'Tesla', 'Powerwall 3', '13.5 kWh nameplate/usable · ~100% DoD · LFP · integrated inverter', None, None, None, None, 13.5, 100, None, None, None, 9500, 'Equipment cost only; installed cost runs higher.'),
    ('EG4 PowerPro WallMount 14.3kWh', 'Battery', 'EG4', 'PowerPro WallMount AllWeather', '14.3 kWh nameplate (280Ah @ 48V) · ~95-100% usable · LiFePO4', None, None, None, None, 14.3, 95, None, None, None, 4000, ''),
    ('Battle Born 100Ah 12V', 'Battery', 'Battle Born', 'BB10012', '1.28 kWh nameplate · ~90-100% DoD · LiFePO4 · 12V', None, None, None, None, 1.28, 90, None, None, None, 870, 'Common for small off-grid/RV-style banks; stack multiple in parallel/series.'),
    ('Fortress Power eVault Max 18.5kWh', 'Battery', 'Fortress Power', 'eVault Max 18.5kWh', '18.5 kWh nameplate (360Ah) · 80% DoD · LiFePO4', None, None, None, None, 18.5, 80, None, None, None, 7500, ''),
    ('SimpliPhi PHI 3.8', 'Battery', 'SimpliPhi (Briggs & Stratton)', 'PHI 3.8', '3.8 kWh nameplate/usable · 100% DoD · LFP', None, None, None, None, 3.8, 100, None, None, None, 3450, 'Common off-grid modular building block.'),
    ('Sol-Ark 15K-2P', 'Inverter', 'Sol-Ark', '15K-2P-N', '12kW continuous (15kW surge) · Max PV input 500V, 3 MPPTs, 19.5kW PV cap · 48V battery · ~97.5% peak eff.', None, None, None, None, None, None, 500, 12000, 97.5, 5000, 'All-in-one hybrid inverter with built-in MPPT.'),
    ('EG4 6000XP', 'Inverter', 'EG4', '6000XP', '6,000W continuous · Max PV input 480V (120-385V MPPT range) · 48V battery · ~99% MPPT / ~93% charge-discharge eff.', None, None, None, None, None, None, 480, 6000, 93, 2150, 'All-in-one hybrid inverter with built-in MPPT.'),
    ('Schneider Conext XW Pro 6848', 'Inverter', 'Schneider Electric', 'XW Pro 6848', '6,800W continuous · pairs with external Conext MPPT charge controller (no built-in PV input) · 48V · 95.7% eff.', None, None, None, None, None, None, None, 6800, 95.7, 4750, 'Inverter/charger only — requires a separate charge controller.'),
    ('Victron Quattro 48/5000', 'Inverter', 'Victron Energy', 'Quattro 48/5000/70-100/100', '~4,000W continuous (5000VA) · pairs with external Victron MPPT · 48V · ~94-96% eff.', None, None, None, None, None, None, None, 4000, 95, 3750, 'Inverter/charger only — requires a separate charge controller.'),
    ('Outback Radian GS8048A', 'Inverter', 'Outback Power', 'GS8048A-01', '8,000W continuous · pairs with external FLEXmax MPPT · 48V · ~95-96% eff.', None, None, None, None, None, None, None, 8000, 95.5, 4750, 'Inverter/charger only — requires a separate FLEXmax charge controller.'),
    ('Midnite Classic 150', 'Charge Controller', 'Midnite Solar', 'Classic 150', 'Max PV input 150V · 96A output (12-48V systems)', None, None, None, None, None, None, 150, None, None, 725, ''),
    ('Victron SmartSolar MPPT 150/100', 'Charge Controller', 'Victron Energy', 'SmartSolar MPPT 150/100-Tr', 'Max PV input 150V · 100A output', None, None, None, None, None, None, 150, None, None, 800, ''),
    ('Victron SmartSolar MPPT 250/100', 'Charge Controller', 'Victron Energy', 'SmartSolar MPPT 250/100-Tr', 'Max PV input 250V · 100A output', None, None, None, None, None, None, 250, None, None, 1000, 'Higher-voltage variant for longer strings.'),
    ('Outback FLEXmax 100 (AFCI)', 'Charge Controller', 'Outback Power', 'FLEXmax 100', 'Max PV input 300V · 100A output', None, None, None, None, None, None, 300, None, None, 675, ''),
    ('Renogy Rover 60A', 'Charge Controller', 'Renogy', 'Rover 60A', 'Max PV input 150V · 60A output', None, None, None, None, None, None, 150, None, None, 200, 'Budget-tier reference point.'),
    ('Midnite MNEDC50 50A DC Breaker', 'Breaker', 'Midnite Solar', 'MNEDC50', '50A DC-rated breaker', None, None, None, None, None, None, None, None, None, 45, ''),
    ('Midnite MNEPV150 150A DC Breaker', 'Breaker', 'Midnite Solar', 'MNEPV150', '150A DC-rated breaker', None, None, None, None, None, None, None, None, None, 90, ''),
    ('Square D QO250 50A 2-Pole', 'Breaker', 'Square D', 'QO250', '50A 2-pole AC breaker', None, None, None, None, None, None, None, None, None, 25, ''),
    ('Siemens QP230 30A 2-Pole', 'Breaker', 'Siemens', 'QP230', '30A 2-pole AC breaker', None, None, None, None, None, None, None, None, None, 20, ''),
    ('Square D QO 200A 30-Space Load Center', 'Breaker Panel', 'Square D', 'QO130M200PC', '200A main breaker, 30-space/40-circuit load center', None, None, None, None, None, None, None, None, None, 180, ''),
    ('Midnite MNPV6 PV Combiner', 'Breaker Panel', 'Midnite Solar', 'MNPV6', '6-position PV source-circuit combiner', None, None, None, None, None, None, None, None, None, 140, ''),
    ('Square D 125A Sub-Panel', 'Breaker Panel', 'Square D', 'QO112L125GRB', '125A main lug sub-panel, 12-space', None, None, None, None, None, None, None, None, None, 110, ''),
    ('Generac 200A Auto Transfer Switch', 'Controls', 'Generac', 'RXSW200A3', '200A whole-home automatic transfer switch', None, None, None, None, None, None, None, None, None, 700, ''),
    ('Reliance 30A Manual Transfer Switch', 'Controls', 'Reliance Controls', '30310A', '6-circuit manual transfer switch, 30A generator inlet', None, None, None, None, None, None, None, None, None, 350, ''),
    ('Sol-Ark Generator Start Module', 'Controls', 'Sol-Ark', 'Gen-Start Kit', 'Dry-contact auto-generator-start module for Sol-Ark inverters', None, None, None, None, None, None, None, None, None, 150, ''),
    ('Square D 30A Fused AC Disconnect', 'Electrical', 'Square D', 'H221RB', '30A fused non-fusible-option AC disconnect, NEMA 3R', None, None, None, None, None, None, None, None, None, 85, ''),
    ('Midnite MNPV3 Combiner Box', 'Electrical', 'Midnite Solar', 'MNPV3', '3-string PV combiner box, NEMA 3R', None, None, None, None, None, None, None, None, None, 70, ''),
    ('MC4 Connector Pair', 'Electrical', 'Stäubli (Multi-Contact)', 'MC4', 'Standard PV connector pair, per set', None, None, None, None, None, None, None, None, None, 3, ''),
    ('Polaris Insulated Multi-Tap Connector', 'Electrical', 'Polaris', 'IPLD4-4/0', 'Insulated multi-tap connector, 4-port', None, None, None, None, None, None, None, None, None, 15, ''),
    ('NEMA 3R Outdoor Enclosure 24x24x8', 'Enclosure', 'Generic', 'NEMA-3R-24x24x8', 'Outdoor-rated equipment enclosure', None, None, None, None, None, None, None, None, None, 180, ''),
    ('Indoor Battery Cabinet', 'Enclosure', 'Generic', 'Battery-Cab-48', 'Ventilated indoor cabinet for 48V battery banks', None, None, None, None, None, None, None, None, None, 450, ''),
    ('Midnite MNBOX Combiner Enclosure', 'Enclosure', 'Midnite Solar', 'MNBOX', 'Empty enclosure for combiner/breaker assemblies', None, None, None, None, None, None, None, None, None, 120, ''),
    ('Generac Guardian 22kW Standby', 'Generator', 'Generac', 'Guardian 22kW', '22kW air-cooled automatic standby generator', None, None, None, None, None, None, None, None, None, 5500, ''),
    ('Honda EU7000iS Portable Inverter Generator', 'Generator', 'Honda', 'EU7000iS', '7,000W portable inverter generator', None, None, None, None, None, None, None, None, None, 4300, ''),
    ('Champion 12.5kW Dual Fuel Standby', 'Generator', 'Champion', '100294', '12.5kW dual-fuel (LP/NG) standby generator', None, None, None, None, None, None, None, None, None, 3200, ''),
    ('Kohler 20RESCL 20kW Standby', 'Generator', 'Kohler', '20RESCL', '20kW air-cooled automatic standby generator', None, None, None, None, None, None, None, None, None, 5800, ''),
    ('Victron Cerbo GX', 'Monitoring', 'Victron Energy', 'Cerbo GX', 'System monitoring/communication hub, VRM cloud', None, None, None, None, None, None, None, None, None, 300, ''),
    ('Sol-Ark WiFi Monitoring Dongle', 'Monitoring', 'Sol-Ark', 'WiFi Dongle', 'Remote monitoring module for Sol-Ark inverters', None, None, None, None, None, None, None, None, None, 120, ''),
    ('SolarEdge Monitoring Gateway', 'Monitoring', 'SolarEdge', 'Home Gateway', 'Monitoring gateway for optimizer-based systems', None, None, None, None, None, None, None, None, None, 150, ''),
    ('EG4 Communication Hub', 'Monitoring', 'EG4', 'Comm Hub', 'Battery/inverter communication and monitoring module', None, None, None, None, None, None, None, None, None, 100, ''),
    ('Permit Set Printing & Submission', 'Office Supplies', '—', '—', 'Per-job permit document printing/filing', None, None, None, None, None, None, None, None, None, 150, ''),
    ('NEC Placards & Labels Kit', 'Office Supplies', '—', '—', 'Code-required system labeling kit, per job', None, None, None, None, None, None, None, None, None, 60, ''),
    ('Job-Site Signage Kit', 'Office Supplies', '—', '—', 'Warning/disconnect signage, per job', None, None, None, None, None, None, None, None, None, 40, ''),
    ('SolarEdge P401 Power Optimizer', 'Optimizer', 'SolarEdge', 'P401', 'Module-level power optimizer, residential', None, None, None, None, None, None, None, None, None, 45, ''),
    ('SolarEdge P950 Power Optimizer', 'Optimizer', 'SolarEdge', 'P950', 'Module-level power optimizer, higher-power/commercial', None, None, None, None, None, None, None, None, None, 60, ''),
    ('Tigo TS4-A-O Optimizer', 'Optimizer', 'Tigo Energy', 'TS4-A-O', 'Module-level power optimizer, add-on rapid shutdown + optimization', None, None, None, None, None, None, None, None, None, 35, ''),
    ('SolarJack SDS-D-165 Submersible Pump', 'Pumping', 'SolarJack', 'SDS-D-165', 'Solar-direct submersible well pump', None, None, None, None, None, None, None, None, None, 1200, ''),
    ('Grundfos SQFlex 2.5-2', 'Pumping', 'Grundfos', 'SQFlex 2.5-2', 'Solar submersible pump, DC/AC capable', None, None, None, None, None, None, None, None, None, 1800, ''),
    ('Franklin Electric SubDrive SolarPAK', 'Pumping', 'Franklin Electric', 'SubDrive SolarPAK', 'Solar pump + controller package', None, None, None, None, None, None, None, None, None, 2200, ''),
    ('IronRidge XR10 Rail (168in)', 'Racking', 'IronRidge', 'XR10-168', 'Composite roof-mount rail, 14ft', None, None, None, None, None, None, None, None, None, 65, ''),
    ('IronRidge FlashFoot2', 'Racking', 'IronRidge', 'FlashFoot2', 'Flashed roof attachment point, per unit', None, None, None, None, None, None, None, None, None, 12, ''),
    ('Unirac Ground Mount Kit (per panel)', 'Racking', 'Unirac', 'GroundMount', 'Ground-mount racking, per-panel allocation', None, None, None, None, None, None, None, None, None, 220, ''),
    ('DPW Solar Top-of-Pole Mount (4-panel)', 'Racking', 'DPW Solar', 'Pole Mount 4-up', 'Top-of-pole mount for up to 4 panels', None, None, None, None, None, None, None, None, None, 650, ''),
    ('PV Wire 10AWG USE-2/RHW-2 (per ft)', 'Wire', 'Generic', '10AWG PV Wire', 'Sunlight-resistant PV source-circuit wire, per foot', None, None, None, None, None, None, None, None, None, 0.65, ''),
    ('THHN 6AWG Stranded Copper (per ft)', 'Wire', 'Generic', '6AWG THHN', 'Building wire for feeders/branch circuits, per foot', None, None, None, None, None, None, None, None, None, 1.1, ''),
    ('Battery Interconnect Cable 4/0 w/ Lugs (3ft)', 'Wire', 'Generic', '4/0 Welding Cable', 'Pre-lugged battery interconnect cable, 3ft', None, None, None, None, None, None, None, None, None, 45, ''),
    ('MC4 Extension Cable 10AWG 20ft', 'Wire', 'Generic', 'MC4-Ext-20', 'Pre-made PV extension cable with MC4 connectors', None, None, None, None, None, None, None, None, None, 28, ''),
]
